# Generated by Django 2.0.5 on 2018-05-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
    ]
